export const routes = {
  splash: 'Splash',
  onboarding: 'Onboarding',
  addVehicle: 'AddVehicle',
  vehicle: 'Vehicle',
  garage: 'Garage',
  selectLogType: 'SelectLogType',
  addLog: 'AddLog',
  maintenanceHistory: 'MaintenanceHistory',
  updateMileage: 'UpdateMileage',
  shareLink: 'ShareLink',
  editVehicle: 'EditVehicle',
  paywall: 'Paywall',
  account: 'Account',
  auth: 'Auth',
  username: 'Username',
  otpVerification: 'OtpVerification',
  spending: 'Spending',
  transfer: 'Transfer',
  reminderSettings: 'ReminderSettings',
  garageAnalytics: 'GarageAnalytics',
  export: 'Export',
  businessDetails: 'BusinessDetails',
  companySettings: 'CompanySettings',
  setupFlow: 'SetupFlow',
  appFlow: 'AppFlow',
} as const;
